######################################################################
# Automatically generated by qmake (3.0) Mon Mar 5 15:47:37 2018
######################################################################

QT += widgets
TEMPLATE = app
TARGET = PerfecTea_GUI
INCLUDEPATH += .

# Input
HEADERS += mywindow.h title_scr.h
FORMS += mywindow.ui title_scr.ui
SOURCES += main.cpp mywindow.cpp title_scr.cpp
RESOURCES += resource.qrc
