######################################################################
# Automatically generated by qmake (3.0) Tue Feb 20 18:56:21 2018
######################################################################

TEMPLATE = app
TARGET = PerfecTea_GUI
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
FORMS += mywindow.ui
SOURCES += main.cpp mywindow.cpp
RESOURCES += resource.qrc
QT += widgets
